# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-19 22:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name="Issue's database id")),
                ('ref', models.CharField(max_length=255, null=True, verbose_name="Issue's reference")),
                ('status', models.CharField(default='open', max_length=20, verbose_name="Issue's status")),
                ('title', models.CharField(max_length=255, verbose_name="Issue's title")),
                ('description', models.TextField(verbose_name="Issue's description")),
                ('solution', models.TextField(null=True, verbose_name="Issue's solution")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_issues', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
