# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issuecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20, verbose_name="Issue's status"),
        ),
    ]
