# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-07 22:40
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20171206_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name="Issue's description"),
        ),
    ]
