# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-07 22:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20171207_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name="Comment's body"),
        ),
    ]
