# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-09 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('issues', '0005_auto_20171207_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
