# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-21 22:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171118_1809'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyApplicationLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('DAY', 'DAY'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR')], max_length=15)),
                ('max_users', models.IntegerField(verbose_name='Maximum number of users')),
                ('duration_days', models.IntegerField(verbose_name='Duration days of the license')),
            ],
        ),
        migrations.AddField(
            model_name='companyapplicationlicense',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.License'),
        ),
        migrations.AlterUniqueTogether(
            name='companyapplicationlicense',
            unique_together=set([('company', 'application', 'active')]),
        ),
    ]
