# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20171203_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyapplicationlicense',
            unique_together=set([]),
        ),
    ]
