# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-09 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20171209_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='users',
            field=models.ManyToManyField(related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
