# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-11 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0005_auto_20170514_1141'),
        ('applications', '0007_remove_permission_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('oauth2_provider.accesstoken',),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('oauth2_provider.application',),
        ),
    ]
