# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-08 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='destination_id',
            new_name='destination',
        ),
    ]
