# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-08 14:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20171208_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name="Message's body"),
        ),
    ]
