# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name="Company's database id")),
                ('name', models.CharField(max_length=255, verbose_name='Name of Company')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Company slug')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Account email', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text="Account's holder password", max_length=56),
        ),
    ]
