# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171012_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users', to='users.Company'),
            preserve_default=False,
        ),
    ]
