# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-09 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_remove_permission_users'),
        ('users', '0006_companyrule_userrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(related_name='users', to='applications.Permission'),
        ),
    ]
