# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-11 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='main_company',
            field=models.BooleanField(default=False),
        ),
    ]
