# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-11 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userrule_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRuleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.CharField(blank=True, max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserRule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userrule',
            name='users',
            field=models.ManyToManyField(through='users.UserRuleUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
