# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-11 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171211_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrule',
            name='users',
            field=models.ManyToManyField(related_name='rules', through='users.UserRuleUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
