# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-11 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_userrule_argument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userruleuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
